version: "3"

volumes:
  prometheus_data: {}
  grafana_storage: {}
  serversync: 

services:
  modbusClient:
    image: a904871/hlfmodbus:ClienteSyncTest
    container_name: cliente_pymodbus
    environment: 
      - IP_SERVER=172.19.0.2
      #- IP_SERVER=192.168.1.39
    depends_on: 
      - modbusServer
    volumes:
      - ../../../Docker/ClienteSync/ClienteSync.py:/ClienteSync.py
      - ../../app:/etc/HFBapp
      - ../../connection-profile:/etc/connection-profile
      - ../../crypto-material:/etc/crypto-material
      - ../../chaincode:/etc/chaincode
      
    ports: 
      - 5021:5021
    

      
  modbusServer:
    image: a904871/hlfmodbus:ServSyncTest
    container_name: server_pymodbus
    volumes:
      - ../../../Docker/ServidorSync/ServidorSync.py:/ServidorSync.py
      - ../../../Docker/ServidorSync/sinc.py:/usr/local/lib/python3.8/dist-packages/pymodbus/server/sync.py
      - ../../app:/etc/HFBapp
      - ../../connection-profile:/etc/connection-profile
      - ../../crypto-material:/etc/crypto-material
      - ../../chaincode:/etc/chaincode
    
    ports: 
      - 5020:5020


